### ISSUE TITLE
Roadmap/Improvements

### ISSUE THREAD

**Issue by aitikgupta** [aitikgupta/swi-ml#1]
Since the initial release, these could be straight up improvements:
- [ ] 1. Make [matplotlib](https://matplotlib.org/) a runtime dependency.
- [ ] 2. Use the OO-API for [matplotlib](https://matplotlib.org/), instead of fluid `pyplot` API 
- [ ] 3. Unify the logging system, with only a single public API
 3.1 `set_verbose`
 3.2 (Current implementation uses 2 APIs, `set_logging_level` and `logger.setLevel`)
- [ ] 4.  Setup CI/CD
